# Generated by Django 2.0.7 on 2018-07-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180706_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='blog_name',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='topic_name',
        ),
    ]
